### PR TITLE
Event data viz

### PR DESCRIPTION
**Pull request by amylittleyang**

### CODE REVIEW

**Comment by amylittleyang** [comment]
All conflicts resolved;  
Moved controllers to separate files;  
Router file renamed from js/main.js to js/app.js. Write controller functions in different files and add reference in app.js.

**Comment by suyashkumar** [comment]
@vishnumenon take a look at this/discuss with @amylittleyang and merge! I really like the controllers in separate files! Maybe it's better to have them in their own controllers/ folder? Will we still be able to load them? Not super familiar with Angular's module system (I'm most familiar with require.js)

**Comment by vishnumenon** [comment]
@amylittleyang @suyashkumar Yeah I definitely prefer this organization too, much cleaner -- and yeah, I'm pretty sure we can move the controllers to their own folder, sounds good

**Comment by vishnumenon** [comment]
@amylittleyang @suyashkumar So this merge slightly broke the graphing in the comparison page bc it drops the 'nvd3' angular module import, i added it back in and also moved the controllers to their own folder in the comparison-view branch

**Pull request merged**
