### PR TITLE
Modified form data to be compatible with server schema

### PR DESCRIPTION
**Pull request by amylittleyang**

### CODE REVIEW

**Comment by amylittleyang** [comment]
Also got a few errors when trying to run the app locally.
I'm running node js v5.1.0. There were a few warnings after I run npm install but no errors.
Am I missing something? :(

image

image

**Comment by suyashkumar** [comment]
This error is because it cannot connect to MongoDB! Do you have it running?

If you want to run it locally make sure you have MongoDB installed and a directory called /data/db and run

sudo service mongod start
:)

**Comment by amylittleyang** [comment]
Okay problem solved!  I have mongodb downloaded but did not create /data/db.
I ran the app locally and tried to POST an event using the html form. Server responded with 200 but the event is not dumped to the database for some reason. I checked the database with mongo shell and the only collection in the db was "startup_log". 

Does it mean the event object is still not conformant with the schema ??

**Comment by suyashkumar** [comment]
Take a look at the actual server response (just console.log it)—it’ll tell you if there are some things that aren’t conformant. It might return 200 but the response itself might have some other information. Ideally we should have it not return 200 in an error circumstance. @vishnumenon

**Comment by vishnumenon** [comment]
@suyashkumar Oh right, oops, sorry, totally overlooked that -- I'll fix that right away and send a pull request

**Comment by vishnumenon** [comment]
@suyashkumar Ok, I sent a pull request, should be fixed

**Comment by suyashkumar** [comment]
Thanks Vishnu--I'll merge it later tonight or you can merge it yourself if you've tested it!

**Comment by amylittleyang** [comment]
Merry Christmas everyone! @suyashkumar @vishnumenon  @patriciaa 
I just debugged the angular POST and have it tested locally with mongodb running. Got 200 from server and actually saw the objects go into the database. Yay! Merged the fork with master myself, so should have no conflicts with base this time.

**Comment by z3t1** [comment]
:+1:

**Comment by z3t1** [comment]
:+1:

**Comment by suyashkumar** [comment]
Well done Amy! Good job :)

**Pull request merged**
